config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "landing_pages#home"

  get "/create_room", to: "rooms#create", as: "create_room"
  get "/staging_areas/:slug", to: "rooms#staging_area", as: "staging_area"
  get "/rooms/:slug", to: "rooms#show", as: "room"

  # Redirect all 404's to root path
  get "*path" => redirect("/")

  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  validates :slug, presence: true, uniqueness: true
  before_validation :initialize_slug

  # time a player has to draw in seconds.
  TIME_LIMIT = 90

  has_many :users, -> {
    where.not(name: nil).order("id ASC")
  }

  has_many :users_in_staging, -> {
    where(name: nil)
  }, class_name: 'User'

  def scoreboard
    self.users.sort_by{ |u| -u.score }
  end

  def update_hint(guess)
    guess = guess.strip.downcase
    return if self.current_word.nil? || guess.include?(self.current_word)

    updated_hint = self.hint
    guess.each_char.with_index do |char, index|
      if char == self.current_word[index]
        updated_hint[index] = char
      end
    end

    update!(hint: updated_hint)
  end

  def start_game
    self.users.each do |user|
      user.set_score(0)
    end
    update!(game_started: true)
  end

  def end_game
    self.end_turn
    update!(round: 1, game_started: false)
  end

  def start_turn(word)
    word = word.strip.downcase
    update!(current_word: word, hint: word.gsub(/[\w]/, '-'))
    self.users.each do |user|
      user.update!(guessed_correctly: false)
    end
  end

  def end_turn
    update!(current_word: nil, hint: nil, time_remaining: TIME_LIMIT)
  end

  def everyone_guessed_correctly?
    # self.users.count - 1 because the user currently drawing is excluded.
    self.users.count{ |u| u.guessed_correctly? } == (self.users.count - 1)
  end

  def can_draw?(id)
    (id == self.drawer_id) && self.game_started? && !self.current_word.nil?
  end

  def correct_guess?(guess)
    self.current_word == guess
  end

  def decrement_time_remaining
    seconds = self.time_remaining
    update!(time_remaining: (seconds - 1))
  end

  # Returns the user removed from room.
  def remove_user(user)
    return user if user.nil? || !self.users.include?(user)

    # argument is passed-by-value
    self.users.find_by(id: user.id).destroy!
  end

  # Sets and returns the user model record of the next drawer.
  # If room contains no users, nil is returned.
  # If room contains only one user, that user record is returned.
  def set_next_drawer
    return if self.users.empty?
    if self.drawer_id.nil?
      update!(drawer_id: self.users.first.id)
      return self.users.first
    end
    unless self.users.map(&:id).include?(self.drawer_id)
      # if we are here it probably means the current drawer left the room.
      update!(drawer_id: self.users.first.id)
      return
    end

    index = self.users.map(&:id).index(self.drawer_id)
    # made it back to the first user.
    if ((index + 1) % self.users.count) == 0
      self.update!(round: self.round + 1)
    end
    update!(drawer_id: self.users[(index + 1) % self.users.count].id)
    self.users[(index + 1) % self.users.count]
  end

  def current_drawer_name
    self.users.find(self.drawer_id).name
  rescue
    nil
  end

private
  def initialize_slug
    return if self.slug.present?
    self.slug = SecureRandom.urlsafe_base64(5).downcase
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :room, optional: false
  after_destroy :room_clean_up

  def set_as_guessed_correctly
    update!(guessed_correctly: true)
  end

  def set_score(score)
    update!(score: score)
  end

  def clear_score
    set_score(0)
  end

  def in_staging?
    self.name.nil?
  end

private
  # Will the last person leaving the room turn out the lights!
  # This callback ensures that we don't end up with rooms with empty users.
  def room_clean_up
    if self.room.users.count == 0 && self.room.users_in_staging.count == 0
      self.room.destroy
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  scope :easy, -> { where(difficulty: "Easy").pluck(:name, :difficulty) }
  scope :medium, -> { where(difficulty: "Medium").pluck(:name, :difficulty) }
  scope :hard, -> { where(difficulty: "Hard").pluck(:name, :difficulty) }

  ##
  # @return [Word] three random words, one of each difficulty.
  def self.random_option_set
    [Word.easy.sample, Word.medium.sample, Word.hard.sample]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home
    cookies.delete :user_id
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    cookies.delete :user_id
    room = Room.create!
    redirect_to(room_path(slug: room.slug))
  end

  def staging_area
    @room = Room.find_by(slug: params[:slug])
    if @room.nil?
      flash[:error] = "Room code '#{params[:slug]}' is invalid."
      redirect_to(root_path)
      return
    end
    if @user.nil?
      @user = User.create!(room: @room)
      cookies.encrypted[:user_id] = @user.id
    end
  end

  def show
    @room = Room.find_by(slug: params[:slug])
    # Redirect user back to root path if the slug provided does not match to
    # an active room.
    if @room.nil?
      flash[:error] = "Room code '#{params[:slug]}' is invalid."
      redirect_to(root_path)
      return
    end

    @user = User.find_by(id: cookies.encrypted[:user_id])
    # Redirect user to staging area if user information is not set.
    if @user.nil? || @user.name.nil?
      @user = User.create!(room: @room)
      cookies.encrypted[:user_id] = @user.id
      redirect_to(staging_area_path(slug: @room.slug))
      return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/landing_pages/home.html.slim
p.intro.unselectable.u-pin-center A free, ad-free, online multiplayer drawing and guessing game.
.u-container.u-container--column.u-container--justify-center.u-container--align-center.u-container--full-height
  .u-container.u-my30
    = link_to 'Host Game', create_room_path,
      class: 'c-button c-button--primary u-mx18 unselectable'
    = link_to 'Join Game', nil,
      class: "c-button c-button--secondary u-mx18 unselectable #{flash.any? ? "c-button--pressed" : ""}"
  form.c-form__search class="#{flash.any? ? "invalid-input" : "hidden"}"
    = text_field_tag :search_game_room_input, nil,
      placeholder: 'Enter room code...', autocomplete: :off
    button
      i.fa.fa-search
  - if flash.any?
    - flash.each do |key, value|
      p.error = value

javascript:
  const joinButton = document.querySelector('.c-button--secondary');
  const searchInput = document.querySelector('#search_game_room_input');
  const searchButton = document.querySelector('form > button');

  joinButton.addEventListener('click', (event) => {
    event.preventDefault();
    joinButton.classList.add('c-button--pressed');
    const form = document.querySelector('form');
    if (form.classList.contains('hidden')) {
      form.classList.remove('hidden');
      joinButton.focus();
    }
  });
  searchButton.addEventListener('click', (event) => {
    event.preventDefault();
    if (searchInput.value.length > 0) {
      window.location.href = `/rooms/${searchInput.value}`;
    }
  });
  searchInput.addEventListener('keydown', (event) => {
    if (event.code === 'Enter') {
      const sanitizedInput = event.target.value.replace(/<(.|\n)*?>/g, '');
      event.preventDefault();
      if (sanitizedInput.length > 0) {
        window.location.href = `/rooms/${sanitizedInput}`;
      }
    }
  });

app/views/landing_pages/room.html.slim
table
  tr.first-row
    td.first-column.u-centered.td--muted
      .u-container.u-container--justify-center
        .clipboard
          code copy room link
          button
            i.fa.fa-clipboard
    td.second-column.u-centered.td--muted
      h2#word
    td.third-column.u-centered.td--muted
      h2#time-remaining 60s
  tr.second-row
    td
      ul.player-container id="#{@user.id}"
    td.canvas-container
      .u-overlay-container.hidden
        .u-container.u-container--column.u-container--align-center.u-container--full-height.u-container--justify-center
          h2.u-my10 Choose your word!
          .u-overlay-card-container
            - Word.random_option_set.each do |word|
              .c-card.c-card__word.animate-pop-in
                p.title = word.name
                p.subtitle = word.difficulty
      canvas
    td
      .chat-container
        ul.message-container
        .typing-message
          p
            i
        form
          = search_field_tag :chat_input, nil, autocomplete: :off
  tr.third-row
    td.u-centered.td--muted
      = link_to 'Start Game', nil, id: 'start-game',
        class: 'c-button c-button--tertiary hidden'
    td.td--muted
      #drawing-palette.u-container.u-container--justify-around.hidden
        .u-container
          #000000.palette-element.palette-element__color.palette-element__color--black
          #FF0000.palette-element.palette-element__color.palette-element__color--red
          #FFA500.palette-element.palette-element__color.palette-element__color--orange
          #FFEA00.palette-element.palette-element__color.palette-element__color--yellow
          #008000.palette-element.palette-element__color.palette-element__color--green
          #0000FF.palette-element.palette-element__color.palette-element__color--blue
          #800080.palette-element.palette-element__color.palette-element__color--purple
          #A52A2A.palette-element.palette-element__color.palette-element__color--brown
          #C0C0C0.palette-element.palette-element__color.palette-element__color--silver
          #FFFFFF.palette-element.palette-element__color.palette-element__color--white
        .u-container.u-container--align-center
          button.palette-element.palette-element__undo-button.palette-element-hidden
            i.fa.fa-arrow-left
          button.palette-element.palette-element__redo-button.palette-element-hidden
            i.fa.fa-arrow-right
          button.palette-element.palette-element__clear-button
            i.fa.fa-trash
    td.u-centered.td--muted
      p#round-information Round #{@user.room.round} of 3

javascript:
  document.querySelector('.clipboard').addEventListener('click', () => {
    navigator.clipboard.writeText(window.location.href)
      .then(() => {
        let buttonIcon = document.querySelector('.clipboard > button > i');
        let label = document.querySelector('.clipboard > code');
        buttonIcon.classList.remove('fa-clipboard');
        buttonIcon.classList.add('fa-check');
        buttonIcon.classList.add('success');
        label.innerText = 'copied!';
        setTimeout(() => {
          buttonIcon.classList.remove('fa-check');
          buttonIcon.classList.remove('success');
          buttonIcon.classList.add('fa-clipboard');
          label.innerText = 'copy room link';
        }, 2000);
      })
      .catch((err) => console.error(`Error copying to clipboard: ${err}`));
  });

app/views/landing_pages/staging_area.html.slim
.u-container.u-container--full-height.u-container--column.u-container--justify-center.u-container--align-center
  #room-information.u-container.u-container--column.u-my30.hidden
    h2.u-centered.u-my10 = "Players in room '#{@room.slug}'"
    .player-staging-container
  form.c-form__search
    = search_field_tag :name_input, nil, placeholder: 'Enter name...', autocomplete: :off
    button
      i.fa.fa-paper-plane
  p.error

app/views/layouts/_head.html.slim
head
  title Doodle It!
  meta name="viewport" content="width=device-width, initial-scale=1"
  link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
  link rel="icon" type="image/png" href="https://img.icons8.com/color/16/paint-palette-with-brush.png" sizes="16x16"
  link rel="icon" type="image/png" href="https://img.icons8.com/color/32/paint-palette-with-brush.png" sizes="32x32"
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags

app/views/layouts/application.html.slim
doctype html
html
  = render partial: 'layouts/head'
  body
    header
      .title
        h1.unselectable Doodle It!
    main
      = yield
    footer
      = link_to 'https://github.com/karamvirr',
        target: '_blank', rel: 'noopener'
        i.fa.fa-brands.fa-github
      .vertical-partition
      = link_to 'https://www.linkedin.com/in/rai/',
        target: '_blank', rel: 'noopener'
        i.fa.fa-brands.fa-linkedin-in

app/views/rooms/show.html.slim
.game
  .wrapper
    .topbar
      .clipboard
        code copy room link
        button
          i.fa.fa-solid.fa-copy
      h2#word = (@room.drawer_id == @user.id) ? @room.current_word : @room.hint
      h2#time-remaining #{@room.time_remaining}s
    .players
      .player-name.hidden id="#{@user.name}"
      .player-id.hidden id="#{@user.id}"
      ul.player-container
    .canvas
      canvas width="800" height="600"
      .u-overlay.hidden
        .u-container.u-container--column.u-container--align-center.u-container--full-height.u-container--justify-center
          h2.u-my10
          .u-card-container
    .chat
      ul.messages
      .typing-message
        p
          i
      form
        = text_field_tag :chat_input, nil, autocomplete: :off,
          placeholder: "Chat or make a guess..."
    .start-button
      = link_to "Start Game", nil, id: "start-game",
        class: "c-button c-button--tertiary \
          #{"hidden" unless (@room.drawer_id == @user.id) && !@room.game_started}"
    .palette.hidden--grid-cell
      .button-group
        .color-options
          #000000.palette-element.palette-element__color.palette-element__color--black
          #FF0000.palette-element.palette-element__color.palette-element__color--red
          #FFA500.palette-element.palette-element__color.palette-element__color--orange
          #FFEA00.palette-element.palette-element__color.palette-element__color--yellow
          #008000.palette-element.palette-element__color.palette-element__color--green
          #0000FF.palette-element.palette-element__color.palette-element__color--blue
          #800080.palette-element.palette-element__color.palette-element__color--purple
          #A52A2A.palette-element.palette-element__color.palette-element__color--brown
          #C0C0C0.palette-element.palette-element__color.palette-element__color--silver
          #FFFFFF.palette-element.palette-element__color.palette-element__color--white
        .action-button-group
          button.palette-element.palette-element__fill-button
            i.fa-solid.fa-fill-drip
          button.palette-element.palette-element__clear-button
            i.fa-solid.fa-trash-can
          button.palette-element.palette-element__undo-button.palette-element--hidden
            i.fa-solid.fa-rotate-left
          button.palette-element.palette-element__redo-button.palette-element--hidden
            i.fa-solid.fa-rotate-right
      .slider-container
        input type="range" min="1" max="50" value="10"
        .paint-brush-icon-container
          .paint-brush-icon
          p.paint-brush-size.hidden
    .round
      h3#round-information Round #{@room.round} of 3

javascript:
  const copyToClipboard = (text) => {
    if (window.clipboardData && window.clipboardData.setData) {
      // Internet Explorer-specific code path to prevent textarea being shown
      // while dialog is visible.
      return window.clipboardData.setData('Text', text);
    } else if (document.queryCommandSupported && document.queryCommandSupported('copy')) {
      let textarea = document.createElement('textarea');
      textarea.textContent = text;
      // Prevent scrolling to bottom of page in Microsoft Edge.
      textarea.style.position = 'fixed';
      document.body.appendChild(textarea);
      textarea.select();
      try {
        // Security exception may be thrown by some browsers.
        return document.execCommand('copy');
      } catch (ex) {
        console.warn('Copy to clipboard failed.', ex);
        return prompt('Copy to clipboard: Ctrl+C, Enter', text);
      } finally {
        document.body.removeChild(textarea);
      }
    }
  };
  let locked = false;
  document.querySelector('.clipboard').addEventListener('click', () => {
    if (copyToClipboard(window.location.href) && !locked) {
      let buttonIcon = document.querySelector('.clipboard > button > i');
      let label = document.querySelector('.clipboard > code');
      buttonIcon.classList.toggle('fa-clipboard');
      buttonIcon.classList.toggle('fa-check');
      buttonIcon.classList.toggle('success');
      label.innerText = 'copied!';
      locked = true;
      setTimeout(() => {
        buttonIcon.classList.toggle('fa-check');
        buttonIcon.classList.toggle('success');
        buttonIcon.classList.toggle('fa-clipboard');
        label.innerText = 'copy room link';
        locked = false
      }, 2000);
    }
  });

app/views/rooms/staging_area.html.slim
.u-container.u-container--full-height.u-container--column.u-container--justify-center.u-container--align-center
  #room-information.u-container.u-container--column.u-my30
    h3.u-centered.u-my10 = "Players in room '#{@room.slug}' (#{@room.users.count})"
    .player-staging-container
      - @room.users.each do |user|
        .c-card.animate-pop-in
          p.title = user.name
  form.c-form__search
    = text_field_tag :name_input, nil, placeholder: "Enter name...",
      autocomplete: :off
    button
      i.fa.fa-paper-plane
  p.error